### ISSUE TITLE
Don't use `-webkit-font-smoothing: antialiased` globally

### ISSUE THREAD

**Issue by ivancuric** [sindresorhus/modern-normalize#19]
https://www.zachleat.com/web/font-smooth/
http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

While it can be used to manually fix some light text on dark backgrounds on Macs, it should't be used on the entire page. It often leads to overly thin text with smaller weights, such as this example:

![image](https://user-images.githubusercontent.com/2827047/36073809-ce1130e8-0f36-11e8-8073-c79f87f87ebf.png)

If you look at how DirectWrite and Cocoa work on Windows and Mac native elements, they use subpixel aa on normal DPI screens, and default to greyscale on high DPI screens. The same is true with Chrome, which disable subpixell AA when the device DPR is over 2.  
Twitter did a similar thing on their site:

```css
@media screen and (-webkit-min-device-pixel-ratio: 2), screen and (min-resolution: 2dppx) {
	body {
		-moz-osx-font-smoothing: grayscale;
		-webkit-font-smoothing: antialiased;
	}
}
```
