### ISSUE TITLE
`h1` style contradicting comment

### ISSUE THREAD

**Issue by HarryPhillips** [sindresorhus/modern-normalize#23]
```CSS
/**
 * Correct the font size and margin on `h1` elements within `section` and
 * `article` contexts in Chrome, Firefox, and Safari.
 */

h1 {
	font-size: 2em;
	margin: 0.67em 0;
}
```

Noticed my `h1` elements were being reduced in size unexpectedly. Is this supposed to be:
```CSS
article h1,
section h1 {
	font-size: 2em;
	margin: 0.67em 0;
}
```
