### ISSUE TITLE
Provide system fonts

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/modern-normalize#3]
Are there any downsides to setting this by default?

```css
body {
	font-family:
		'-apple-system',
		'system-ui',
		'BlinkMacSystemFont',
		'Segoe UI',
		'Roboto',
		'Helvetica Neue',
		'Arial',
		'sans-serif',
		'Apple Color Emoji',
		'Segoe UI Emoji',
		'Segoe UI Symbol';
}
```

Users then get good defaults but can override it with their own `body` selector if they want.

Alternatively, if this gets a lot of resistance, we could provide a CSS variable, so users who want it can just do:

```css
body {
	font-family: var(--system-fonts);
}
```

Thoughts?

*(If you 👎 please also share your thoughts on why)*
