### ISSUE TITLE
box-sizing: inherit

### ISSUE THREAD

**Issue by franciscop-invast** [sindresorhus/modern-normalize#30]
The `box-sizing: border-box;` fix is one of the first normalizing techniques I use when starting from scratch. But since I discovered [the improvement by CSS-Tricks](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/) and Paul Irish [improved the original post](https://www.paulirish.com/2012/box-sizing-border-box-ftw/), this is the best modern recommendation:

```css
/* apply a natural box layout model to all elements, but allowing components to change */
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

So, my suggestion here is to update the style to follow that. I can do a PR if needed.
