### ISSUE TITLE
Outdated `:-moz-focusring` makes form elements less accessible

### ISSUE THREAD

**Issue by LeoniePhiline** [sindresorhus/modern-normalize#55]
The package applies an outdated inaccessible focus ring to form elements in firefox:

```css
/**
Restore the focus styles unset by the previous rule.
*/

:-moz-focusring {
	outline: 1px dotted ButtonText;
}
```

This thin dotted gray line is inaccessible, outdated. Browsers have updated their default focus styles to be much more accessible, including Firefox.

Here an unstyled, focused textarea (without `modern-normalize`):

![image](https://user-images.githubusercontent.com/22329650/123082859-c9d22800-d41f-11eb-8018-5cdf0875f38e.png)

https://codepen.io/rickymetz/pen/ZrbXqJ

It would be fantastic if modern-normalize could undo the custom application of an inaccessible legacy Firefox focus style.
