### ISSUE TITLE
Only show dotted underline on abbr[title] if @media (supports: hover) media query

### ISSUE THREAD

**Issue by coliff** [sindresorhus/modern-normalize#62]
Currently we have this:

```css
abbr[title] {
	text-decoration: underline dotted;
}
```
This means that abbr tags have dotted underline even on iPhone and iPad where its impossible to see the title as browser doesn't support hover - even with a mouse connected.

I propose to change this to:

```
abbr[title] {
  text-decoration: none;
}

@media (supports: hover) {
  abbr[title] {
    text-decoration: underline dotted;
  }
}
```
