### ISSUE TITLE
font-variation-settings is not inherited for button, input, etc. when using variable fonts

### ISSUE THREAD

**Issue by rahatbd** [sindresorhus/modern-normalize#71]
Should using `font: inherit` be appropriate so that `font-variation-settings` is inherited by button, input, etc. if the font is variable?

```css
body {
    font-family: "Recursive", sans-serif;
    font-variation-settings: "CASL" 1, "CRSV" 1, "slnt" var(--recursive-slant, 0), "MONO" var(--recursive-mono, 0);
}
```

```diff
button,
input,
optgroup,
select,
textarea {
-       font-family: inherit; /* 1 */
+       font: inherit; /* 1 */
	font-size: 100%; /* 1 */
	line-height: 1.15; /* 1 */
	margin: 0; /* 2 */
}
```
