### ISSUE TITLE
Test that <abbr> is styled correctly in next Safari

### ISSUE THREAD

**Issue by atjn** [sindresorhus/modern-normalize#87]
Safari currently does not style \<abbr\> elements with a dotted underline. There is a bug to fix this for the next version of Safari: https://bugs.webkit.org/show_bug.cgi?id=277889

We need to check later that the bug has been fixed. If for whatever reason the bug is not fixed in Safari, we can fix it here by adding something along the lines of:

```css
abbr[title], acronym[title] {
    -webkit-text-decoration: dotted underline;
}
```

We would need to test that this actually works as expected.
