### ISSUE TITLE
Remove `optgroup` element

### ISSUE THREAD

**Issue by cevdetardaharan** [sindresorhus/modern-normalize#93]
In `modern-normalize.css` file, there is a reset for form elements:
```css
/**
1. Change the font styles in all browsers.
2. Remove the margin in Firefox and Safari.
*/

button,
input,
optgroup,
select,
textarea {
	font-family: inherit; /* 1 */
	font-size: 100%; /* 1 */
	line-height: 1.15; /* 1 */
	margin: 0; /* 2 */
}
```

`button, `input`, `select` and `textarea` seem fine but `optgroup` is unnecessary; why you may ask, because `optgroup` should be a child element of `select` and `optgroup` should be a parent element of `option` element, we can remove it to take advantage of cascading which `select` element does when it inherits.
